AllCops:
  Exclude:
    - db/**
    - db/*/**
    - bin/spring
    - config/initializers/devise.rb

Documentation:
  Enabled: false

Metrics/LineLength:
  Max: 120

Rails:
  Enabled: true

Style/BlockComments:
  Exclude:
    - spec/spec_helper.rb

Style/Lambda:
  Enabled: false
