AllCops:
  Exclude:
    - db/*
    - db/**/*
    - bin/spring
    - config/initializers/devise.rb
    - vendor/*
    - vendor/**/*

Documentation:
  Enabled: false

Metrics/AbcSize:
  Max: 30

Metrics/BlockLength:
  Exclude:
    - spec/*/**

Metrics/LineLength:
  Max: 120

Rails:
  Enabled: true

Style/BlockComments:
  Exclude:
    - spec/spec_helper.rb

Style/Lambda:
  Enabled: false
