dist: trusty
sudo: required
language: ruby

script:
  - xvfb-run bundle exec rake check

services:
  - postgresql

before_script:
  - cp config/database.yml.travis config/database.yml
  - psql -c 'create database travis_ci_test;' -U postgres
